version: '3'
services:
  dbvs:
    image:
      "mariadb:focal"
    environment:
      MARIADB_USER: "user"
      MARIADB_PASSWORD: "user"
      MARIADB_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306/tcp"
    volumes:
      - "./db/data/mariadb:/var/lib/mysql"

  phpmyadmin:
    image:
      "phpmyadmin:latest"
    environment:
      PMA_USER: "root"
      PMA_PASSWORD: "root"
    ports:
      - "8080:80/tcp"
    links:
      - "dbvs:db"
