version: '3.4'

services:
 dbvs:
   image:
     "mysql:latest"
   environment:
     MYSQL_USER: "user"
     MYSQL_PASSWORD: "user"
     MYSQL_ROOT_PASSWORD: "root"
     TZ: "Europe/Vilnius"
   ports:
     - "3306:3306/tcp"
   volumes:
     - "./db/data/mysql:/var/lib/mysql"

 phpmyadmin:
    image:
      "phpmyadmin:latest"
    environment:
      PMA_USER: "root"
      PMA_PASSWORD: "root"
    ports:
      - "8080:80/tcp"
    links:
      - "dbvs:db"