// <auto-generated />
using System;
using Ktu.T120B178.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ktu.T120B178.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Ktu.T120B178.Api.Entities.DemoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Condition")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Deletable")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("DemoEntityGroupId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("DemoEntityGroupId");

                    b.ToTable("DemoEntities", (string)null);
                });

            modelBuilder.Entity("Ktu.T120B178.Api.Entities.DemoEntityGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("DemoEntityGroups", (string)null);
                });

            modelBuilder.Entity("Ktu.T120B178.Api.Entities.DemoEntity", b =>
                {
                    b.HasOne("Ktu.T120B178.Api.Entities.DemoEntityGroup", "DemoEntityGroup")
                        .WithMany("DemoEntities")
                        .HasForeignKey("DemoEntityGroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("DemoEntityGroup");
                });

            modelBuilder.Entity("Ktu.T120B178.Api.Entities.DemoEntityGroup", b =>
                {
                    b.Navigation("DemoEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
